# Railway config for Bebop RFQ service
# Rename this to railway.toml when deploying the bebop service

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "yarn bebop"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
